name: SIT CICD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
          port: ${{ secrets.SERVERPORT }}
          script: |
            cd EventLoopAPP/
            sudo kill -9 `sudo lsof -t -i:19002`
            git pull
            yarn
            npx expo start --tunnel
            sudo kill -9 `sudo lsof -t -i:22`
